### ISSUE TITLE
IP rotation doesn't work

### ISSUE THREAD

**Issue by kpcyrd** [ustayready/CredKing#1]
I've modified the script to display the public IP that is in use by the lambda, and it seems "rotating IP addresses with each request." doesn't work properly. Each region has it's own public IP, but attempts that are scheduled on the same region use the same public IP until it is rotated by aws after a couple of hours.

Is there anything I'm missing?

**Comment by ustayready** [comment]
It only rotates based on region at the moment. AWS optimizes execution so that lambdas in the same region share. At most, you get one IP per region. We are working on finding ways to force lambda containers to use alternative egress addresses.
